CREATE DATABASE test;

USE test;

CREATE TABLE test
(
    id    INT PRIMARY KEY AUTO_INCREMENT,
    value VARCHAR(50)
);


INSERT INTO test (value)
VALUES (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID()),
       (UUID())
